version: '3.8'

services:
  react-app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true
